#include "stdint.h"
#include "vkcode.h"

// íﬂ√Ë¥a”≥…‰±Ì
static char _kedvice_scancodes[] = {
  VK_NULL, VK_ESCAPE, VK_1, VK_2, VK_3, VK_4, VK_5, VK_6,
  VK_7, VK_8, VK_9, VK_0, VK_SEPARATOR, VK_NULL, VK_BACK, VK_TAB,
  VK_Q, VK_W, VK_E, VK_R, VK_T, VK_Y, VK_U, VK_I,
  VK_O, VK_P, VK_NULL, VK_NULL, VK_RETURN, VK_LEFT, VK_A, VK_S,
  VK_D, VK_F, VK_G, VK_H, VK_J, VK_K, VK_L, VK_NULL,
  VK_NULL, VK_NULL, VK_LSHIFT, VK_NULL, VK_Z, VK_X, VK_C, VK_V,
  VK_B, VK_N, VK_M, VK_NULL, VK_NULL, VK_NULL, VK_RSHIFT, VK_NULL,
  VK_LMENU, VK_SPACE, VK_CAPITAL, VK_F1, VK_F2, VK_F3, VK_F4, VK_F5,
  VK_F6, VK_F7, VK_F8, VK_F9, VK_F10, VK_NUMLOCK, VK_SCROLL, VK_NUMPAD7,
  VK_NUMPAD8, VK_NUMPAD9, VK_NULL, VK_NUMPAD4, VK_NUMPAD5, VK_NUMPAD6, VK_NULL, VK_NUMPAD1,
  VK_NUMPAD2, VK_NUMPAD3, VK_NUMPAD0, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_F11,
  VK_F12, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL,
  VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL,
  VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL,
  VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL,
  VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL, VK_NULL
};

char __stdcall
_kdevice_keyboard_map_scancode(uint8_t uScanCode) {

  if (uScanCode < 0x80) {
    return _kedvice_scancodes[uScanCode];
  }
  return VK_NULL;
}
